services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      # Anda bisa menambahkan variabel .env lainnya di sini atau di UI Dokploy
    volumes:
      - staging_storage:/var/www/html/storage
      - staging_bootstrap:/var/www/html/bootstrap/cache
    networks:
      - dokploy-network

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  staging_storage:
  staging_bootstrap:

networks:
  dokploy-network:
    external: true
