services:
  web:
    image: triangle-pos:latest
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - mailpit
    networks:
      - triangle-network

  db:
    platform: "linux/amd64"
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - triangle-network

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: triangle-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit_data:/data
    networks:
      - triangle-network

networks:
  triangle-network:
    driver: bridge

volumes:
  dbdata:
  mailpit_data:
